name: DEPLOY WITH FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: setup node
      uses: actions/setup-node@master

    - name: Installing project dependencies
      id: install
      run: npm install

    - name: Building the project
      if: steps.install.outcome == 'success'
      id: build
      run: npm run build

    - name: git-ftp push
      if: steps.build.outcome == 'success'
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftps://ftp.fabriziotornatore.com
        user: ${{ secrets.FTP_USR }}
        password: ${{ secrets.FTP_PWD }}
        localDir: "dist"
        remoteDir: "www.fabriziotornatore.com"
        forceSsl: true